# Generated by Django 3.2.7 on 2021-12-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_attendance_report_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_report',
            old_name='subject',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='attendance_report',
            old_name='user',
            new_name='username',
        ),
    ]
