# Generated by Django 3.2.7 on 2021-12-24 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20211224_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_report',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='supportQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfQuery', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('problemDesc', models.CharField(max_length=300)),
                ('value', models.CharField(default='Open', max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
