# Generated by Django 3.2.7 on 2021-12-27 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_deployment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='attendance_report',
            table='Attendance Report',
        ),
        migrations.AlterModelTable(
            name='deployment_model',
            table='Deployment Model',
        ),
        migrations.AlterModelTable(
            name='supportqueries',
            table='Support Query',
        ),
    ]
