# Generated by Django 3.2.7 on 2021-12-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211227_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_report',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
