# Generated by Django 3.2.7 on 2021-12-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_attendance_report_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_report',
            name='initial_date',
            field=models.DateTimeField(default=None),
        ),
    ]
