# Generated by Django 3.2.7 on 2021-12-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_attendance_report_initial_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_report',
            name='initial_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
