# Generated by Django 3.2.7 on 2021-12-27 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_attendance_report_initial_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_report',
            name='initial_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 27, 18, 24, 40, 163140)),
        ),
    ]
