# Generated by Django 3.2.7 on 2021-12-27 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_attendance_report_initial_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_report',
            name='initial_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 27, 22, 17, 3, 830906)),
        ),
        migrations.AlterField(
            model_name='supportqueries',
            name='value',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
    ]
