# Generated by Django 3.2.7 on 2021-12-27 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211227_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_report',
            name='initial_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 27, 22, 35, 8, 614950)),
        ),
    ]
