# Generated by Django 3.2.7 on 2021-12-27 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_attendance_report_initial_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_report',
            name='initial_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 27, 22, 41, 19, 267636)),
        ),
    ]
